export const architectures=Object.freeze([
 {title:'Classical pitot-static',chain:['Airflow / atmosphere','Pitot + static pressure','Pneumatic lines','Diaphragm / capsule / VSI pressure lag','Mechanical linkage','ASI / ALT / VSI'],note:'Pressure is sensed; airspeed, altitude and vertical speed are inferred. The VSI uses time-dependent static-pressure behavior.'},
 {title:'Modern Air Data',chain:['Airflow / atmosphere','Pitot + static pressure','Pressure transducers','Electrical representation + conceptual digital conversion','Air Data Computer / Air Data Module','Digital flight parameters → avionics data → PFD'],note:'The measurands continue across technologies. Pt/Ps are sensor inputs; the displayed flight parameters are computed outputs.'},
 {title:'Classical gyro',chain:['Aircraft motion / orientation','Mechanical gyro','Gimbals / restrained gyro','Relative motion or precession / spring restraint','Mechanical display linkage','AI / HI / TC'],note:'AI uses a stabilized vertical reference; HI uses a directional reference. TC senses angular rate; this app uses Bank only as a proxy.'},
 {title:'Modern attitude / heading',chain:['Aircraft motion / acceleration','Electronic inertial sensors','Electronic sensor / reference data','AHRS attitude / heading processing','Digital attitude / heading solution + avionics data','PFD'],note:'Electronic sensing plus computation replaces the mechanical stabilized reference concept. Attitude and heading still need appropriate references.'}
]);
export const components=Object.freeze([
 ['world','Physical world / sources','Pitot probe: supplies total pressure Pt. Static port: samples ambient static pressure Ps. Motion and orientation belong to a separate inertial/reference path.'],
 ['sensor','Electronic sensing','Pressure transducer: a pressure-responsive sensing diaphragm converts pressure into an electrical representation. Electronic rate gyro: responds to angular rate, not orientation directly. Accelerometer: senses specific force; gravity-related attitude aiding depends on motion assumptions. No numerical rate or acceleration stream is simulated.'],
 ['electrical','Electrical signal / digital conversion','Sensor information is conditioned and converted to numerical data conceptually. This aircraft architecture includes that stage without circuit models, voltages, bit-depth exercises or a generic ADC laboratory.'],
 ['computer','Air Data Computer / AHRS','Air Data Computer or Air Data Module: interprets sensed pressures and available data to compute air-data parameters. AHRS (Attitude and Heading Reference System): processes inertial and reference information for attitude / heading. Heading aiding can provide a directional datum; a magnetometer is one conceptual example, with no magnetic model here. These are distinct systems, not one generic flight computer.'],
 ['data','Digital avionics data','Numerical values travel between aircraft systems over a conceptual avionics data path. Values also need validity / reliability information. No bus protocol or redundancy-management logic is simulated.'],
 ['display','Primary Flight Display','PFD: integrates airspeed, altitude, attitude, heading and vertical-speed information. A digital indication can be plausible but wrong: INDICATION ≠ TRUTH. This display is an original educational layout, not manufacturer-specific avionics.']
]);
export const changed=Object.freeze(['Sensing technology','Signal representation','Processing','Transmission','Cockpit presentation','System integration']);
export const unchanged=Object.freeze(['Underlying physical quantities','Need for appropriate references','Need for valid sensor information','Distinction between measured inputs and inferred outputs','Possibility of sensor / reference failure']);
export const airNote='Direct sensor inputs: Pt / Ps. Computed / inferred outputs: airspeed, altitude and vertical-speed related information. Altitude is inferred from static pressure; there is no direct electronic altitude sensor in this model. Airspeed reuses the existing fixed-density teaching relation; no TAS or Mach computation is added. Electronic pressure sensing and digital conversion are conceptual, with no duplicate pressure or atmosphere calculations.';
export const ahrsNote='Rate gyroscopes sense angular rate; accelerometers sense specific force. AHRS processing forms an attitude / heading solution with appropriate references and aiding. Here the shared Pitch / Bank / Heading state represents an ideal supplied solution; it is not calculated from fabricated sensor streams. No strapdown integration, Kalman filtering, inertial navigation or real turn-rate physics is implemented.';
export const validityNote='DATA VALUE + DATA VALIDITY / RELIABILITY. HEALTHY TEACHING REFERENCE means ideal sources and solutions are assumed in this workspace, not independently validated. Invalid pressure source → unreliable air-data computation → unreliable PFD parameter. Degraded inertial / heading reference → unreliable attitude / heading solution. Phase 5 demonstrates upstream fault propagation; digital presentation cannot repair bad inputs. No new avionics failure or redundancy simulation is introduced.';
export const vsiNote='The PFD and the classical comparison reuse the same healthy VSI lag output. This is the existing educational pressure-trend representation, not a new digital vertical-speed algorithm. Altitude and Vertical Speed remain independent controls; altitude is not differentiated or integrated. Active manual faults still affect the main cockpit; this workspace shows a separate healthy reference from the same physical flight state.';
export const roadmapNote='Roadmap update: the generic measurement-science content formerly planned as Phases 6–11 has moved to the separate interactive Measurement & Instrumentation course project. This repository stays focused on aircraft instrumentation; Phase 12 bridges classical instruments to Air Data, AHRS and digital flight presentation.';
