import {components as aiComponents} from '../../internal/attitude/content.js';
import {components as hiComponents} from '../../internal/heading/content.js';
import {components as tcComponents} from '../../internal/turn/content.js';
export const titles={attitude:'Attitude Indicator',heading:'Heading Indicator',turn:'Turn Coordinator'};
export const proxyNote='In this educational interface, Bank is used as a proxy input to demonstrate the direction and magnitude of rate-gyro response. A real Turn Coordinator responds to angular rate, not bank angle.';
export const chains={
  attitude:[['INPUT','Aircraft pitch and bank orientation'],['REFERENCE','Ideal stabilized vertical gyro'],['RELATIVE MOTION','Aircraft case vs gyro reference'],['CONVERSION','Gimbal / mechanical display linkage'],['OUTPUT','Pitch and bank indication']],
  heading:[['INPUT','Aircraft heading / yaw orientation'],['REFERENCE','Ideal directional gyro'],['RELATIVE MOTION','Aircraft case vs gyro reference'],['CONVERSION','Gear / compass-card rotation'],['OUTPUT','Heading under a fixed lubber line']],
  turn:[['PHYSICAL INPUT','Aircraft angular rate'],['TEACHING CONTROL IN THIS APP','Bank used only as a proxy'],['SENSING ELEMENT','Restrained rate gyro'],['CONVERSION','Precession + spring-restraint deflection'],['OUTPUT','Turn-rate indication']]
};
export const steps={
  attitude:[['gc-body','The aircraft changes pitch and/or bank.'],['gc-vertical','The stabilized gyro reference tends to retain its orientation.'],['gc-relative','The aircraft case moves relative to that reference.'],['gc-conversion','The mechanism converts relative orientation into display motion.'],['gc-output','The pilot reads pitch and bank from the horizon display.']],
  heading:[['gc-body','The aircraft changes heading.'],['gc-directional','The directional gyro provides an inertial reference.'],['gc-relative','The aircraft case rotates relative to the gyro.'],['gc-card','The mechanism rotates the compass card.'],['gc-lubber','The fixed lubber line indicates heading.']],
  turn:[['gc-body','Aircraft rotational motion provides the gyro input. Bank is only the app proxy.'],['gc-precession','Gyroscopic precession produces a tendency to deflect.'],['gc-spring','A spring provides restraint.'],['gc-rate','The equilibrium deflection represents turn-rate response.'],['gc-output','The display converts gyro deflection into a turn indication.']]
};
const reused=(source,id,target,label)=>{const entry=source.find(c=>c[0]===id);return [target,label||entry[1],entry[2]];};
export function components(instrument) {
  const common=[['gc-body','Aircraft body','The aircraft-fixed case moves with aircraft orientation. AI uses pitch and bank; HI uses heading. A real TC senses angular rate; Bank is only this app’s teaching proxy.'],['gc-relative','Relative case motion','The aircraft case moves relative to an ideal gyro reference. AI uses a vertical reference; HI uses a directional reference. A TC instead has restrained rate response.'],['gc-conversion','Mechanical conversion','Conceptual linkage converts relative orientation or restrained deflection into cockpit indication. No new dynamics are calculated.'],['gc-output',instrument==='turn'?'Turn indication':'Display output',instrument==='turn'?'The miniature aircraft represents turn indication using the existing bounded Bank-proxy mapping. It does not measure bank angle.':'The existing cockpit renderer shows the selected instrument indication.']];
  if(instrument==='attitude')return [...common,['gc-vertical','Vertical gyro reference','Ideal stabilized world-up reference for pitch and bank. This is distinct from the HI directional / heading reference.'],...['spin','outer','inner'].map(id=>reused(aiComponents,id,`gc-${id}`))];
  if(instrument==='heading')return [...common,['gc-directional','Directional gyro reference','Ideal stabilized azimuth / heading reference, initially aligned north. This is distinct from the AI vertical reference.'],...['spin','outer','inner','card','lubber'].map(id=>reused(hiComponents,id,`gc-${id}`))];
  return [...common.filter(([id])=>id!=='gc-relative'),['gc-rate','Restrained rate gyro','A bounded, quasi-static educational response represents restrained-gyro equilibrium. A real instrument senses angular rate, not bank angle.'],['gc-precession','Gyroscopic precession','Angular-rate input produces a tendency to deflect about a different permitted axis from the input and spin axes. Detailed torque dynamics are not modeled.'],reused(tcComponents,'spin','gc-spin'),reused(tcComponents,'spring','gc-spring','Spring restraint'),['gc-ball','Inclinometer ball','Separate subsystem responding to gravity and lateral acceleration in a real instrument. The existing ball stays centered in this app; no slip/skid physics is invented.']];
}
