export const titles={attitude:'Attitude Indicator',heading:'Heading Indicator',turn:'Turn Coordinator'};
export const steps={
 normal:['The gyro reference / response is healthy.','Existing Phase 3 models convert relative orientation or restrained response into indication.'],
 drive:['Gyro drive is initially healthy.','Drive is lost at the captured activation state.','Educational effectiveness decays exponentially with elapsed time.','AI/HI increasingly favor captured indication; TC gyro response decreases.','At low effectiveness the reference is explicitly unreliable, even if the indication looks plausible.','The symptom indicates gyro/reference degradation rather than a change in aircraft state.'],
 drift:['The directional gyro initially agrees with reference heading.','A signed educational drift rate is introduced.','Angular error accumulates with elapsed time.','The card indication gradually separates from reference heading.','An indication can remain smooth and responsive while still being wrong.'],
 bias:['The stabilized vertical reference is initially correct.','A deterministic pitch/bank reference bias is introduced.','Aircraft attitude is compared with an incorrect vertical reference.','The display remains responsive but becomes systematically wrong.','A reference offset differs from complete drive loss.'],
 effectiveness:['The restrained rate gyro responds normally.','Gyro effectiveness is reduced.','The same real angular-rate input would produce less response.','The teaching display under-responds; the inclinometer is unchanged.','Bank remains only the educational proxy, not the actual measurand.']
};
export const questions=[['HI moves smoothly but slowly departs from reference heading. Which fault fits?','Directional gyro drift: smooth motion does not guarantee an accurate reference.'],['AI responds to pitch/bank with a persistent offset. Is complete drive loss the best diagnosis?','A biased vertical reference is more consistent with this deterministic offset than complete drive loss.'],['TC response is smaller for the same teaching input, while the ball stays unchanged. Which subsystem is implicated?','The restrained rate-gyro response, not the separate inclinometer. Bank is only the app proxy for demonstrating angular-rate sensing.']];
export const assumptions='Educational deterministic degradation, not manufacturer-specific failure behavior. AI/HI drive loss blends toward captured indication rather than random tumbling or magnetic north. Effectiveness = exp(−elapsed / decay time), set to zero after eight decay times; 5% or less is labelled unreliable. Clearing recovers instantly in this teaching model. Reduced motion does not stop fault time evolution. No exact rotor RPM, erection dynamics, Earth-rate correction, magnetic slaving, supply plumbing or electrical architecture is modeled.';
