import {candidates} from './model.js';
export const familyNames=Object.freeze({'pitot-static':'Pitot-static',gyroscopic:'Gyroscopic'});
export const hints=Object.freeze([
 'Which indications change unexpectedly? Compare affected and unaffected instruments using the independently controlled flight state.',
 'ASI, Altimeter and VSI share static pressure. AI uses a vertical reference; HI uses a directional reference. TC has a separate restrained rate gyro and ball.',
 'Try to distinguish a trapped signal, a persistent offset, a growing error, and a loss of response. A responsive display can still be wrong.',
 'Change one control while holding the others fixed, or advance simulation time. Airspeed response separates pitot trapping from a healthy total-pressure path; growing heading error differs from weakening reference hold.'
]);
export const explanations=Object.freeze({
 'blocked-pitot':{fits:'Total pressure is captured at activation while static pressure stays live. ASI loses airspeed-driven Pt response but can still change with altitude; the pointer itself is not frozen.',common:'Altimeter and VSI keep live Ps. Normal behavior in those two makes a shared static-path blockage unlikely.',confirm:'Change airspeed at fixed altitude, then altitude at fixed airspeed.',whyNot:'A trapped Pt path cannot explain an Altimeter tied to stale Ps or an isolated gyro error.'},
 'blocked-static':{fits:'The same captured Ps reaches ASI, Altimeter and VSI. The Altimeter stays near activation altitude; ASI compares live Pt with trapped Ps. The existing VSI lag tends toward zero.',common:'Three pressure instruments share one static transmission path. This is a common-source fault, not evidence of three failed display mechanisms.',confirm:'Change altitude and the independent Vertical Speed control; observe the delivered Ps and VSI settling.',whyNot:'If the Altimeter follows altitude and VSI follows the independent trend control, shared static trapping is inconsistent.'},
 'pitot-leak':{fits:'The educational leak moves delivered Pt toward current Ps. ASI under-reads with severity, while Altimeter and VSI remain connected to live Ps.',common:'Only the ASI receives total pressure. Normal Altimeter/VSI behavior narrows the investigation to the pitot side.',confirm:'Change airspeed at fixed altitude. A leaking signal still responds, unlike trapped Pt.',whyNot:'This narrowly defined leak cannot freeze the Altimeter or create a gyro-reference error.'},
 'hi-drift':{fits:'Directional-reference error accumulates with elapsed simulation time while heading response remains smooth. Signed error crosses north using shortest-angle comparisons.',common:'An HI-only growing error points to its directional reference, not the AI vertical reference or pressure plumbing.',confirm:'Advance time at fixed heading, then change heading across north. Compare growth of error with loss of response.',whyNot:'Drive loss weakens reference hold toward captured heading; drift adds accumulating error without reducing heading sensitivity.'},
 'ai-bias':{fits:'The aircraft attitude is compared against a biased vertical reference. Pitch and bank remain responsive with a deterministic offset, subject to the existing display limits.',common:'AI vertical-reference bias is isolated from HI directional reference and TC rate-gyro response.',confirm:'Change pitch and bank within the display limits; check whether the offset persists without growing over time.',whyNot:'Drive loss progressively reduces reference hold; a fixed reference bias remains responsive rather than decaying.'},
 'tc-effectiveness':{fits:'The same Bank proxy produces a smaller bounded gyro response. A real TC senses angular rate; Bank is only this app’s teaching input.',common:'Only the restrained rate-gyro response changes. The separate inclinometer ball remains centered; no slip/skid physics is inferred.',confirm:'Change Bank proxy in both directions and compare normalized response. The ball should remain unchanged.',whyNot:'Pressure-path faults and AI/HI reference faults do not reduce the TC gyro response.'},
 'hi-drive':{fits:'Educational effectiveness decays with deterministic elapsed time. Indication tends toward captured heading as directional-reference hold is lost; it never snaps to magnetic north.',common:'This is an individual HI drive injection. No shared vacuum or electrical supply architecture is modeled.',confirm:'Change heading and advance time. Look for declining response, rather than a smooth additive drift.',whyNot:'Directional drift produces accumulating offset while preserving heading response; it does not reduce reference effectiveness.'},
 'ai-drive':{fits:'Educational effectiveness decays and attitude indication increasingly favors the captured activation attitude. This deterministic representation is not a prediction of every real failed AI.',common:'This is an individual AI drive injection. No shared drive failure across instruments is assumed.',confirm:'Change pitch/bank after activation, then advance time and observe loss of reference hold.',whyNot:'A vertical-reference bias preserves response with an offset; drive loss progressively reduces useful hold.'}
});
export function suggestedExperiment(session){
 const id=session.scenario.id;
 if(id==='more-evidence'||/speed|discrepancy/.test(id))return {state:{airspeed:session.state.airspeed<140?160:90},text:'Change airspeed while holding altitude.'};
 if(/path|height/.test(id))return {state:{altitude:session.state.altitude<5000?7000:3000,verticalSpeed:1000},seconds:3,text:'Change altitude by at least 2000 ft; set the independent trend control to +1000 ft/min.'};
 if(id==='response-strength')return {state:{bank:session.state.bank>0?-30:30},text:'Change Bank proxy and observe TC response.'};
 if(/offset|attitude/.test(id))return {state:{pitch:session.state.pitch>0?-10:10,bank:session.state.bank>0?-20:20},text:'Change pitch and bank within the display limits.'};
 return {state:{heading:session.state.heading>180?1:359},seconds:10,text:'Rotate heading across north and observe another 10 s.'};
}
export function debrief(session){
 const id=session.scenario.hiddenFaultId,c=candidates[id],ex=explanations[id];
 return {diagnosis:c.name,category:c.category,timePattern:c.timePattern,...ex,location:`${c.instrument} · ${c.element} · ${c.component}`,trust:'INDICATION ≠ TRUTH: a display can be responsive but biased, frozen, degraded, drifting, or plausible but wrong.'};
}
